<!-- import important libraries -->

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
from wordcloud import WordCloud, STOPWORDS

print("Everything is working!")

Everything is working!

In [6]:
import sys
!{sys.executable} -m pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.65.0-cp313-cp313-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.0)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.2-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.3 MB 7.3 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.3 MB 10.2 MB/s eta 0:00:01
   ---------------------- ----------------- 5.2/9.3 MB 8.8 MB/s eta 0:00:01
   ------------------------- -------------- 6.0/9.3 MB 7.6 MB/s eta 0:00:01
   ------------------------------ --------- 7.1/9.3 MB 7.2 MB/s eta 0:00:01
   -------------------------------- ------- 7.6/9.3 MB 6.8 MB/s eta 0:00:01
   ------------------------------------- -- 8.7/9.3 MB 6.0 MB/s eta 0:00:01
   -------------------------------------- - 8.9/9.3 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 4.6 MB/s  0:00:02
Downloading contourpy-1.4.0-cp313-cp313-win_amd64.whl (234 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.65.0-cp313-cp313-win_amd64.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.5 MB ? eta -:--:--
   ------------ --------------------------- 0.8/2.5 MB 2.3 MB/s eta 0:00:01
   --------------------- ------------------ 1.3/2.5 MB 2.3 MB/s eta 0:00:01
   ----------------------------- ---------- 1.8/2.5 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 2.4/2.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 2.2 MB/s  0:00:01
Downloading kiwisolver-1.5.1-cp313-cp313-win_amd64.whl (70 kB)
Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/7.2 MB 2.6 MB/s eta 0:00:03
   ---- ----------------------------------- 0.8/7.2 MB 2.3 MB/s eta 0:00:03
   ------- -------------------------------- 1.3/7.2 MB 2.0 MB/s eta 0:00:03
   -------- ------------------------------- 1.6/7.2 MB 2.0 MB/s eta 0:00:03
   ---------- ----------------------------- 1.8/7.2 MB 1.8 MB/s eta 0:00:04
   ------------- -------------------------- 2.4/7.2 MB 1.9 MB/s eta 0:00:03
   ----------------- ---------------------- 3.1/7.2 MB 2.1 MB/s eta 0:00:02
   -------------------- ------------------- 3.7/7.2 MB 2.2 MB/s eta 0:00:02
   ------------------------ --------------- 4.5/7.2 MB 2.3 MB/s eta 0:00:02
   --------------------------- ------------ 5.0/7.2 MB 2.4 MB/s eta 0:00:01
   ------------------------------ --------- 5.5/7.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 6.3/7.2 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 6.8/7.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.2 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 2.3 MB/s  0:00:03
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------- ---------------------------- 2/7 [kiwisolver]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------- ----------------- 4/7 [cycler]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.65.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-12.3.0 pyparsing-3.3.2

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\fateh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [7]:
import sys
!{sys.executable} -m pip install matplotlib seaborn wordcloud

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.11.2)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting wordcloud
  Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: tzdata in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\fateh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl (306 kB)
Installing collected packages: wordcloud, seaborn

   ---------------------------------------- 0/2 [wordcloud]
   ---------------------------------------- 0/2 [wordcloud]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   -------------------- ------------------- 1/2 [seaborn]
   ---------------------------------------- 2/2 [seaborn]

Successfully installed seaborn-0.13.2 wordcloud-1.9.6

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\fateh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [8]:
import matplotlib
print(matplotlib.__version__)

3.11.2

In [11]:
df = pd.read_csv("hotel_bookings_data.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_weekdays_nights,adults,...,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
0,Resort Hotel,0,342,2017,September,27,1,0,0,2,...,3,No Deposit,NaN,NaN,0,Personal,0.0,0,0,Check-Out
1,Resort Hotel,0,737,2017,September,27,1,0,0,2,...,4,No Deposit,NaN,NaN,0,Personal,0.0,0,0,Check-Out
2,Resort Hotel,0,7,2017,September,27,1,0,1,1,...,0,No Deposit,NaN,NaN,0,Personal,75.0,0,0,Check-Out
3,Resort Hotel,0,13,2017,September,27,1,0,1,1,...,0,No Deposit,304.0,NaN,0,Personal,75.0,0,0,Check-Out
4,Resort Hotel,0,14,2017,September,27,1,0,2,2,...,0,No Deposit,240.0,NaN,0,Personal,98.0,0,1,Check-Out

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 29 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_weekdays_nights        119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  city                            118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  booking_changes                 119390 non-null  int64
 20  deposit_type                    119390 non-null  str
 21  agent                           103050 non-null  float64
 22  company                         6797 non-null    float64
 23  days_in_waiting_list            119390 non-null  int64
 24  customer_type                   119390 non-null  str
 25  adr                             119390 non-null  float64
 26  required_car_parking_spaces     119390 non-null  int64
 27  total_of_special_requests       119390 non-null  int64
 28  reservation_status              119390 non-null  str
dtypes: float64(4), int64(16), str(9)
memory usage: 26.4 MB

In [13]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
hotel,119390,2,City Hotel,79330,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_canceled,119390.0,NaN,NaN,NaN,0.370416,0.482918,0.0,0.0,0.0,1.0,1.0
lead_time,119390.0,NaN,NaN,NaN,104.011416,106.863097,0.0,18.0,69.0,160.0,737.0
arrival_date_year,119390.0,NaN,NaN,NaN,2018.156554,0.707476,2017.0,2018.0,2018.0,2019.0,2019.0
arrival_date_month,119390,12,October,13877,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrival_date_week_number,119390.0,NaN,NaN,NaN,27.165173,13.605138,1.0,16.0,28.0,38.0,53.0
arrival_date_day_of_month,119390.0,NaN,NaN,NaN,15.798241,8.780829,1.0,8.0,16.0,23.0,31.0
stays_in_weekend_nights,119390.0,NaN,NaN,NaN,0.927599,0.998613,0.0,0.0,1.0,2.0,19.0
stays_in_weekdays_nights,119390.0,NaN,NaN,NaN,2.500302,1.908286,0.0,1.0,2.0,3.0,50.0
adults,119390.0,NaN,NaN,NaN,1.856403,0.579261,0.0,2.0,2.0,2.0,55.0
children,119386.0,NaN,NaN,NaN,0.10389,0.398561,0.0,0.0,0.0,0.0,10.0
babies,119390.0,NaN,NaN,NaN,0.007949,0.097436,0.0,0.0,0.0,0.0,10.0
meal,119390,5,Breakfast,92310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,118902,177,Kota Denpasar,48590,NaN,NaN,NaN,NaN,NaN,NaN,NaN
market_segment,119390,8,Online TA,56477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distribution_channel,119390,5,TA/TO,97870,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_repeated_guest,119390.0,NaN,NaN,NaN,0.031912,0.175767,0.0,0.0,0.0,0.0,1.0
previous_cancellations,119390.0,NaN,NaN,NaN,0.087118,0.844336,0.0,0.0,0.0,0.0,26.0
previous_bookings_not_canceled,119390.0,NaN,NaN,NaN,0.137097,1.497437,0.0,0.0,0.0,0.0,72.0
booking_changes,119390.0,NaN,NaN,NaN,0.221124,0.652306,0.0,0.0,0.0,0.0,21.0
deposit_type,119390,3,No Deposit,104641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agent,103050.0,NaN,NaN,NaN,86.693382,110.774548,1.0,9.0,14.0,229.0,535.0
company,6797.0,NaN,NaN,NaN,189.266735,131.655015,6.0,62.0,179.0,270.0,543.0
days_in_waiting_list,119390.0,NaN,NaN,NaN,2.321149,17.594721,0.0,0.0,0.0,0.0,391.0
customer_type,119390,4,Personal,89613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adr,119390.0,NaN,NaN,NaN,101.831122,50.53579,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,NaN,NaN,NaN,0.062518,0.245291,0.0,0.0,0.0,0.0,8.0
total_of_special_requests,119390.0,NaN,NaN,NaN,0.571363,0.792798,0.0,0.0,0.0,1.0,5.0
reservation_status,119390,3,Check-Out,75166,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<!-- START OF THE EDA -->

In [17]:
df_clean = df.copy()

In [20]:
df.shape
df.head()
df.tail()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 29 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_weekdays_nights        119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  city                            118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  booking_changes                 119390 non-null  int64
 20  deposit_type                    119390 non-null  str
 21  agent                           103050 non-null  float64
 22  company                         6797 non-null    float64
 23  days_in_waiting_list            119390 non-null  int64
 24  customer_type                   119390 non-null  str
 25  adr                             119390 non-null  float64
 26  required_car_parking_spaces     119390 non-null  int64
 27  total_of_special_requests       119390 non-null  int64
 28  reservation_status              119390 non-null  str
dtypes: float64(4), int64(16), str(9)
memory usage: 26.4 MB

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_weekdays_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2018.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2017.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2018.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2018.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2019.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2019.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [21]:
df.shape

(119390, 29)

In [22]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_weekdays_nights', 'adults', 'children', 'babies', 'meal',
       'city', 'market_segment', 'distribution_channel', 'is_repeated_guest',
       'previous_cancellations', 'previous_bookings_not_canceled',
       'booking_changes', 'deposit_type', 'agent', 'company',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status'],
      dtype='str')

In [23]:
df.isnull().sum().sort_values(ascending=False)

company                           112593
agent                              16340
city                                 488
children                               4
is_canceled                            0
arrival_date_month                     0
arrival_date_week_number               0
stays_in_weekend_nights                0
arrival_date_day_of_month              0
stays_in_weekdays_nights               0
lead_time                              0
arrival_date_year                      0
hotel                                  0
meal                                   0
babies                                 0
adults                                 0
market_segment                         0
previous_cancellations                 0
previous_bookings_not_canceled         0
distribution_channel                   0
is_repeated_guest                      0
deposit_type                           0
booking_changes                        0
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(33261)

<!-- removing of the duplicate -->

In [25]:
df = df.drop_duplicates()

In [26]:
df.shape

(86129, 29)

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.shape
df = df.drop_duplicates()
df.shape
df.duplicated().sum()

np.int64(0)

In [29]:
df.isnull().sum().sort_values(ascending=False)

company                           81019
agent                             11941
city                                450
children                              4
is_canceled                           0
arrival_date_month                    0
arrival_date_week_number              0
stays_in_weekend_nights               0
arrival_date_day_of_month             0
stays_in_weekdays_nights              0
lead_time                             0
arrival_date_year                     0
hotel                                 0
meal                                  0
babies                                0
adults                                0
market_segment                        0
previous_cancellations                0
previous_bookings_not_canceled        0
distribution_channel                  0
is_repeated_guest                     0
deposit_type                          0
booking_changes                       0
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
dtype: int64

In [30]:
df["company"].value_counts(dropna=False).head(10)

company
NaN      81019
40.0       847
223.0      455
45.0       230
153.0      206
154.0      132
219.0      130
281.0      115
174.0      114
233.0       89
Name: count, dtype: int64

In [31]:
df["agent"].value_counts(dropna=False).head(10)

agent
9.0      28629
240.0    12973
NaN      11941
14.0      3336
7.0       3287
250.0     2774
241.0     1639
28.0      1491
8.0       1376
1.0       1082
Name: count, dtype: int64

In [32]:
df["city"].value_counts(dropna=False).head(10)

city
Kota Denpasar                 26903
Kabupaten Bangka              10303
Kota Yogyakarta                8718
Kota Batu                      7166
Kabupaten Bandung              5279
Kabupaten Kepulauan Seribu     3015
Kota Malang                    2991
Kabupaten Magelang             2070
Kota Jakarta Barat             1983
Kabupaten Belitung             1898
Name: count, dtype: int64

In [33]:
df["children"].value_counts(dropna=False)

children
0.0     77785
1.0      4681
2.0      3583
3.0        75
NaN         4
10.0        1
Name: count, dtype: int64

In [34]:
df["city"] = df["city"].fillna("Unknown")
df["children"] = df["children"].fillna(0)

In [37]:
df.isnull().sum().sort_values(ascending=False)

company                           81019
agent                             11941
lead_time                             0
is_canceled                           0
hotel                                 0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_weekdays_nights              0
adults                                0
children                              0
arrival_date_year                     0
arrival_date_month                    0
meal                                  0
babies                                0
city                                  0
market_segment                        0
previous_cancellations                0
previous_bookings_not_canceled        0
distribution_channel                  0
is_repeated_guest                     0
deposit_type                          0
booking_changes                       0
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
dtype: int64

In [38]:
df.shape

(86129, 29)

In [39]:
df.head()
df.info()

<class 'pandas.DataFrame'>
Index: 86129 entries, 0 to 119389
Data columns (total 29 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           86129 non-null  str
 1   is_canceled                     86129 non-null  int64
 2   lead_time                       86129 non-null  int64
 3   arrival_date_year               86129 non-null  int64
 4   arrival_date_month              86129 non-null  str
 5   arrival_date_week_number        86129 non-null  int64
 6   arrival_date_day_of_month       86129 non-null  int64
 7   stays_in_weekend_nights         86129 non-null  int64
 8   stays_in_weekdays_nights        86129 non-null  int64
 9   adults                          86129 non-null  int64
 10  children                        86129 non-null  float64
 11  babies                          86129 non-null  int64
 12  meal                            86129 non-null  str
 13  city                            86129 non-null  str
 14  market_segment                  86129 non-null  str
 15  distribution_channel            86129 non-null  str
 16  is_repeated_guest               86129 non-null  int64
 17  previous_cancellations          86129 non-null  int64
 18  previous_bookings_not_canceled  86129 non-null  int64
 19  booking_changes                 86129 non-null  int64
 20  deposit_type                    86129 non-null  str
 21  agent                           74188 non-null  float64
 22  company                         5110 non-null   float64
 23  days_in_waiting_list            86129 non-null  int64
 24  customer_type                   86129 non-null  str
 25  adr                             86129 non-null  float64
 26  required_car_parking_spaces     86129 non-null  int64
 27  total_of_special_requests       86129 non-null  int64
 28  reservation_status              86129 non-null  str
dtypes: float64(4), int64(16), str(9)
memory usage: 19.7 MB

In [40]:
df["meal"].value_counts(dropna=False)

meal
Breakfast     67088
No Meal        9442
Dinner         8798
Undefined       454
Full Board      347
Name: count, dtype: int64

In [41]:
df["meal"] = df["meal"].replace("Undefined", "No Meal")

In [42]:
df["meal"].value_counts()

meal
Breakfast     67088
No Meal        9896
Dinner         8798
Full Board      347
Name: count, dtype: int64

In [43]:
(df["adr"] < 0).sum()

np.int64(1)

In [44]:
df["adr"].sort_values(ascending=False).head(10)

48515     5400.00
111403     510.00
15083      508.00
103912     451.50
13142      450.00
13391      437.00
39155      426.25
39568      402.00
39118      397.38
13323      392.00
Name: adr, dtype: float64

In [45]:
(df["adults"] + df["children"] + df["babies"] == 0).sum()

np.int64(165)

In [46]:
df[df["adr"] < 0]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_weekdays_nights,adults,...,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
14969,Resort Hotel,0,195,2019,May,10,5,4,6,2,...,2,No Deposit,273.0,NaN,0,Family,-6.38,0,0,Check-Out

In [47]:
df_clean = df.copy()

# Remove negative ADR
df_clean = df_clean[df_clean["adr"] >= 0]

# Create total guests
df_clean["total_guests"] = (
    df_clean["adults"] +
    df_clean["children"] +
    df_clean["babies"]
)

# Remove bookings with no guests
df_clean = df_clean[df_clean["total_guests"] > 0]

# Remove helper column from final dataset
df_clean = df_clean.drop(columns=["total_guests"])

print("Final shape:", df_clean.shape)

Final shape: (85963, 29)

In [48]:
df_clean.isnull().sum().sort_values(ascending=False)

company                           80875
agent                             11890
lead_time                             0
is_canceled                           0
hotel                                 0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_weekdays_nights              0
adults                                0
children                              0
arrival_date_year                     0
arrival_date_month                    0
meal                                  0
babies                                0
city                                  0
market_segment                        0
previous_cancellations                0
previous_bookings_not_canceled        0
distribution_channel                  0
is_repeated_guest                     0
deposit_type                          0
booking_changes                       0
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
dtype: int64

In [50]:
df_clean.to_csv("hotel_bookings_cleaned.csv", index=False)
df = pd.read_csv("hotel_bookings_cleaned.csv")